import type { Metadata } from 'next';
import './globals.css';
import { Alegreya_Sans } from 'next/font/google';

const alegreyaSans = Alegreya_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '700', '800'], // Add any weights you need
  style: ['normal', 'italic'], // If you need italic styles
});

export const metadata: Metadata = {
  title: 'Продай жилье',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alegreyaSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
